### ISSUE TITLE
How to use siphash24 with Python 3.9?

### ISSUE THREAD

**Issue by l1x** [dnicolodi/python-siphash24#3]
Hi,

I am not sure why this is happening. I am trying to build a AWS Lambda layer containing siphash24. AWS uses an older version of Python. This is how I try to install all the packages into a folder:

```bash
pip install . --python-version "3.9" --platform "manylinux2010" --only-binary=:all: -t python/
```

```bash
Collecting PyJWT==2.4.0
  Using cached PyJWT-2.4.0-py3-none-any.whl (18 kB)
Collecting fastapi==0.79.0
  Using cached fastapi-0.79.0-py3-none-any.whl (54 kB)
Collecting botocore==1.29.69
  Downloading botocore-1.29.69-py3-none-any.whl (10.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 50.2 MB/s eta 0:00:00
Collecting mangum==0.17.0
  Downloading mangum-0.17.0-py3-none-any.whl (17 kB)
INFO: pip is looking at multiple versions of casefy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of airium to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of app to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement siphash24==1.2 (from datafet) (from versions: none)
ERROR: No matching distribution found for siphash24==1.2
```

Is there anything I could do to make siphash compatible with python 3.9 + manylinux2010?

**Comment by l1x** [comment]
I think it is just better to use a custom runtime with Lambda at this stage. I was running into so many issues with 3.9 + libraries like Siphash24 I have decided to do this instead:

https://dev.to/gaborschulz/running-python-311-on-aws-lambda-1i7p

**Comment by dnicolodi** [comment]
The issue is not related to the Python version. Wheels are built for Python 3.7 to 3.11 but for manylinux 2014 / manylinux 2.17. Is really AWS Lambda still on glibc 2.12? The easiest is to just compile it for manylinux 2.12 if you need it.

**Comment by dnicolodi** [comment]
It really seems that AWS Lambda images have a very old glibc. I can add manylunux 2010 to the wheel build matrix, if that helps.

**Comment by l1x** [comment]
> The issue is not related to the Python version. Wheels are built for Python 3.7 to 3.11 but for manylinux 2014 / manylinux 2.17. Is really AWS Lambda still on glibc 2.12? The easiest is to just compile it for manylinux 2.12 if you need it.

Absolutely. Yes they are on glibc 2.12, not sure why. Anyways, Siphash24 was the least of the problem. I ended up creating a docker based lambda function that has python 3.11 and forget that lambda supports python at all. It much less trouble than trying to run our stack on a outdated platform.

Btw. how do you do that compilation? Just clone the repo and python -m build with the right params? I never looked into python compilation for C based python libs.

**Comment by l1x** [comment]
> It really seems that AWS Lambda images have a very old glibc. I can add manylunux 2010 to the wheel build matrix, if that helps.

Could you show me if you can where that build matrix is? I am just curious how python build works for a scenario like this. Anyways, we have moved to python 3.11 + docker because there were several libraries that did not have manylinux 2010.

**Comment by dnicolodi** [comment]
The wheels are built as part of the CI setup on GitHub Actions, here: https://github.com/dnicolodi/python-siphash24/blob/master/.github/workflows/wheels.yml This uses `cibuildwheel` to make sure that the wheel are redistributable accordingly to the manylinux standards.

If you don't need wheels to be uploaded to PyPI or equivalent, just running `python -m build -w` in the source directory produces a wheel valid for the system where you are running the command. Even easier is to use `python -m pip wheel siphash24`. This downloads the source distribution (sdist) from PyPI and builds it locally. Both solutions take care of setting up an ephemeral isolated build environment with the required dependencies.

**Comment by l1x** [comment]
Thanks Daniele, much appreciated.
