### ISSUE TITLE
Add LICENSE file(s)

### ISSUE THREAD

**Issue by moto-timo** [dnicolodi/python-siphash24#4]
Although you declare the licenses in pyproject.toml, it is best practice to also ship the LICENSE file(s) (including building them into the wheel and sdist).

You might also consider defining a HOMEPAGE variable, but that is less standardized.

**Comment by dnicolodi** [comment]
I've added more detailed licensing information in the form of SPDX headers to all source files and I've included the license text in the source distribution. Unfortunately, the wheel Python packaging format does not allow to be very precise with licensing information. In particular, it does not allow to specify two alternative licenses and include the text for both. Nor it allow to specify the license in a "machine readable" way. For this package I opted to use classifiers tags to specify the license. These are parsed by PyPI to show the correct (or as close as correct as possible) licensing information in the PyPI page for the project.
