### ISSUE TITLE
`hexdigest` should return `str`, not `bytes`

### ISSUE THREAD

**Issue by inducer** [dnicolodi/python-siphash24#6]
```
>>> import hashlib as h
>>> h.sha256(b"1234").hexdigest()
'03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4'
>>> import siphash24
>>> siphash24.siphash13(b"1234").hexdigest()
b'479571a95ba46633'
```

Observed with siphash24 1.5, Python 3.12.4.

**Comment by dnicolodi** [comment]
Ops! You are right. I don't know why I thought it should be bytes. Thank you for reporting it.

**Comment by inducer** [comment]
Thank you! And thanks also for working on a release including this fix.

**Comment by dnicolodi** [comment]
Sure. Unfortunately updating the github actions to the latest releases to avoid deprecation warnings broke the job that uploads the wheels on PyPI. I'm fixing it.

**Comment by dnicolodi** [comment]
Release 1.6 is uploaded to PyPI. Please test and let me know.

**Comment by inducer** [comment]
Works well, thanks! (And I can very much relate to the annoying behavior change of Github's artifact uploader actions)

**Comment by dnicolodi** [comment]
I see in the linked merge request for `pytools` that you would like to have `siphash24` available on conda-forge. I never uploaded anything to conda-forge, but I am happy to help to get `siphash24` into conda-forge, if any help is needed.

**Comment by inducer** [comment]
Thanks for spotting that, and for offering to help. I would be happy to add you as a co-maintainer. If you add a comment saying that you'd like to be included [here](https://github.com/conda-forge/staged-recipes/pull/26856), I'll add you. No rush though, I can also always do that once the package is in.
