### ISSUE TITLE
check.py fails on systems where sys.hash_info.algorithm == fnv

### ISSUE THREAD

**Issue by matthiasdiener** [dnicolodi/python-siphash24#8]
See e.g. [this build](https://github.com/conda-forge/siphash24-feedstock/pull/9).

https://github.com/dnicolodi/python-siphash24/blob/6974ea5c8fd1784551c695eb28056e5ab4a9a94e/check.py#L12

```console
$ PYTHONHASHSEED=0 python check.py
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/siphash24_1728932945151/test_tmp/check.py", line 12, in <module>
    siphash = getattr(siphash24, sys.hash_info.algorithm)
AttributeError: module 'siphash24' has no attribute 'fnv'
```

**Comment by dnicolodi** [comment]
That's expected. The script precisely checks that the `siphash24` module returns the same hash for a bytes object as the builtin `hash()` function. But that can be the case only if Python uses the SipHash-13 or SipHash-24 algorithms and the appropriate environment variable is set to force the hash seed to be 0. Why do you think it is a bug?

**Comment by matthiasdiener** [comment]
Thanks for the explanation! I guess I would have expected it to fail more gracefully in that case, instead of this somewhat cryptic error message.

**Comment by dnicolodi** [comment]
It is just a very simple smoke test. It is not an user facing tool. And it is not part of the package tests. Why are you running this script at all?

**Comment by matthiasdiener** [comment]
This script runs as part of the package build in https://github.com/conda-forge/siphash24-feedstock. Perhaps we should not run it there?

**Comment by dnicolodi** [comment]
I don't know why it was though that running it was necessary to validate the build. It definitely does not hurt, and it seems it caught a possible issue with the conda-forge cross-compilation of CPython (however, it seems that it was found independently earlier) thus there may be some value in having it. However, the package test suite should already be enough to cover any important issue with the package build.
